version: '3.8'

services:
  # --- SERVICE 1: Zookeeper ---
  # The "Manager" for Kafka. It keeps track of status.
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # --- SERVICE 2: Kafka ---
  # The "Conveyor Belt".
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper # Kafka won't start until Zookeeper is ready
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # IMPORTANT: This tells external programs (like your Python script) how to connect.
      # We are saying: "If you are outside Docker (localhost), talk to me on port 9092."
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # --- SERVICE 3: Redis ---
  # The "Whiteboard" (Cache).
  redis:
    image: redis:alpine
    container_name: fraud_detection_redis
    ports:
      - "6379:6379"

  # --- SERVICE 4: PostgreSQL ---
  # The "Filing Cabinet" (Storage).
  db:
    image: postgres:15-alpine
    container_name: fraud_detection_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bank_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: